spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitzone
    username: root
    password: 1234
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: b3gncKTwEUjMAWXAhMeqIj+cDpL21HfnVnSIr9ByUOfboyr3JAISohs59itJt9cMo0uvA8I9Xf6U7MQlkKcx8Q==
  expiration: 3600000